### ISSUE TITLE
News Feed keeps breaking 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Institute-for-Public-Policy#1]
The news feed url keeps failing in the Travis build. All news feed views and panel have been set up.

**Comment by CVE82** [comment]
The visibility rule setting within the news landing page panel doesn't give the option to view center nodes, only programs.

**Comment by CVE82** [comment]
I figured it out and fixed, they didn't have a landing page. Added that and the center field in the landing page content type. Will run the build and see...

**Comment by CVE82** [comment]
Sill failing, removed the news/institute-for-public-policy from the config file for now so the rest of my changes will push through.

**Comment by tu-chill** [comment]
seems to be working.

**Comment by CVE82** [comment]
Still blank WC

**Comment by tu-chill** [comment]
I was looking at the program Public Policy :)
