### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Institute-for-Public-Policy#2]
Hey Zac are we able to make the current hero image work if resized? Thanks!

https://github.com/TULiberalArts/Institute-for-Public-Policy/blob/master/media/PA-Capital-Semester-students-with-Gov-Wolf-Slide-Show.png?raw=true

**Comment by ZMcGroarty** [comment]
Nah, I can make a new one if we need though.

**Comment by CVE82** [comment]
=( Okay cool thanks!
